// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PATH/visualizer_protos.proto

package mech.mania.engine.server.communication.visualizer.model;

public final class VisualizerProtos {
  private VisualizerProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface VisualizerChangeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:visualizer.VisualizerChange)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 change_number = 1;</code>
     * @return The changeNumber.
     */
    long getChangeNumber();
  }
  /**
   * Protobuf type {@code visualizer.VisualizerChange}
   */
  public  static final class VisualizerChange extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:visualizer.VisualizerChange)
      VisualizerChangeOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use VisualizerChange.newBuilder() to construct.
    private VisualizerChange(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private VisualizerChange() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new VisualizerChange();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private VisualizerChange(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              changeNumber_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return mech.mania.engine.server.communication.visualizer.model.VisualizerProtos.internal_static_visualizer_VisualizerChange_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return mech.mania.engine.server.communication.visualizer.model.VisualizerProtos.internal_static_visualizer_VisualizerChange_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              mech.mania.engine.server.communication.visualizer.model.VisualizerProtos.VisualizerChange.class, mech.mania.engine.server.communication.visualizer.model.VisualizerProtos.VisualizerChange.Builder.class);
    }

    public static final int CHANGE_NUMBER_FIELD_NUMBER = 1;
    private long changeNumber_;
    /**
     * <code>int64 change_number = 1;</code>
     * @return The changeNumber.
     */
    public long getChangeNumber() {
      return changeNumber_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (changeNumber_ != 0L) {
        output.writeInt64(1, changeNumber_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (changeNumber_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, changeNumber_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof mech.mania.engine.server.communication.visualizer.model.VisualizerProtos.VisualizerChange)) {
        return super.equals(obj);
      }
      mech.mania.engine.server.communication.visualizer.model.VisualizerProtos.VisualizerChange other = (mech.mania.engine.server.communication.visualizer.model.VisualizerProtos.VisualizerChange) obj;

      if (getChangeNumber()
          != other.getChangeNumber()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CHANGE_NUMBER_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getChangeNumber());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static mech.mania.engine.server.communication.visualizer.model.VisualizerProtos.VisualizerChange parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static mech.mania.engine.server.communication.visualizer.model.VisualizerProtos.VisualizerChange parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static mech.mania.engine.server.communication.visualizer.model.VisualizerProtos.VisualizerChange parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static mech.mania.engine.server.communication.visualizer.model.VisualizerProtos.VisualizerChange parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static mech.mania.engine.server.communication.visualizer.model.VisualizerProtos.VisualizerChange parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static mech.mania.engine.server.communication.visualizer.model.VisualizerProtos.VisualizerChange parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static mech.mania.engine.server.communication.visualizer.model.VisualizerProtos.VisualizerChange parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static mech.mania.engine.server.communication.visualizer.model.VisualizerProtos.VisualizerChange parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static mech.mania.engine.server.communication.visualizer.model.VisualizerProtos.VisualizerChange parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static mech.mania.engine.server.communication.visualizer.model.VisualizerProtos.VisualizerChange parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static mech.mania.engine.server.communication.visualizer.model.VisualizerProtos.VisualizerChange parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static mech.mania.engine.server.communication.visualizer.model.VisualizerProtos.VisualizerChange parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(mech.mania.engine.server.communication.visualizer.model.VisualizerProtos.VisualizerChange prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code visualizer.VisualizerChange}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:visualizer.VisualizerChange)
        mech.mania.engine.server.communication.visualizer.model.VisualizerProtos.VisualizerChangeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return mech.mania.engine.server.communication.visualizer.model.VisualizerProtos.internal_static_visualizer_VisualizerChange_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return mech.mania.engine.server.communication.visualizer.model.VisualizerProtos.internal_static_visualizer_VisualizerChange_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                mech.mania.engine.server.communication.visualizer.model.VisualizerProtos.VisualizerChange.class, mech.mania.engine.server.communication.visualizer.model.VisualizerProtos.VisualizerChange.Builder.class);
      }

      // Construct using mech.mania.engine.server.communication.visualizer.model.VisualizerProtos.VisualizerChange.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        changeNumber_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return mech.mania.engine.server.communication.visualizer.model.VisualizerProtos.internal_static_visualizer_VisualizerChange_descriptor;
      }

      @java.lang.Override
      public mech.mania.engine.server.communication.visualizer.model.VisualizerProtos.VisualizerChange getDefaultInstanceForType() {
        return mech.mania.engine.server.communication.visualizer.model.VisualizerProtos.VisualizerChange.getDefaultInstance();
      }

      @java.lang.Override
      public mech.mania.engine.server.communication.visualizer.model.VisualizerProtos.VisualizerChange build() {
        mech.mania.engine.server.communication.visualizer.model.VisualizerProtos.VisualizerChange result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public mech.mania.engine.server.communication.visualizer.model.VisualizerProtos.VisualizerChange buildPartial() {
        mech.mania.engine.server.communication.visualizer.model.VisualizerProtos.VisualizerChange result = new mech.mania.engine.server.communication.visualizer.model.VisualizerProtos.VisualizerChange(this);
        result.changeNumber_ = changeNumber_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof mech.mania.engine.server.communication.visualizer.model.VisualizerProtos.VisualizerChange) {
          return mergeFrom((mech.mania.engine.server.communication.visualizer.model.VisualizerProtos.VisualizerChange)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(mech.mania.engine.server.communication.visualizer.model.VisualizerProtos.VisualizerChange other) {
        if (other == mech.mania.engine.server.communication.visualizer.model.VisualizerProtos.VisualizerChange.getDefaultInstance()) return this;
        if (other.getChangeNumber() != 0L) {
          setChangeNumber(other.getChangeNumber());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        mech.mania.engine.server.communication.visualizer.model.VisualizerProtos.VisualizerChange parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (mech.mania.engine.server.communication.visualizer.model.VisualizerProtos.VisualizerChange) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long changeNumber_ ;
      /**
       * <code>int64 change_number = 1;</code>
       * @return The changeNumber.
       */
      public long getChangeNumber() {
        return changeNumber_;
      }
      /**
       * <code>int64 change_number = 1;</code>
       * @param value The changeNumber to set.
       * @return This builder for chaining.
       */
      public Builder setChangeNumber(long value) {
        
        changeNumber_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 change_number = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearChangeNumber() {
        
        changeNumber_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:visualizer.VisualizerChange)
    }

    // @@protoc_insertion_point(class_scope:visualizer.VisualizerChange)
    private static final mech.mania.engine.server.communication.visualizer.model.VisualizerProtos.VisualizerChange DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new mech.mania.engine.server.communication.visualizer.model.VisualizerProtos.VisualizerChange();
    }

    public static mech.mania.engine.server.communication.visualizer.model.VisualizerProtos.VisualizerChange getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<VisualizerChange>
        PARSER = new com.google.protobuf.AbstractParser<VisualizerChange>() {
      @java.lang.Override
      public VisualizerChange parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new VisualizerChange(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<VisualizerChange> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<VisualizerChange> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public mech.mania.engine.server.communication.visualizer.model.VisualizerProtos.VisualizerChange getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_visualizer_VisualizerChange_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_visualizer_VisualizerChange_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034PATH/visualizer_protos.proto\022\nvisualiz" +
      "er\")\n\020VisualizerChange\022\025\n\rchange_number\030" +
      "\001 \001(\003BU\n7mech.mania.engine.server.commun" +
      "ication.visualizer.modelB\020VisualizerProt" +
      "os\252\002\007MM26.IOb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_visualizer_VisualizerChange_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_visualizer_VisualizerChange_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_visualizer_VisualizerChange_descriptor,
        new java.lang.String[] { "ChangeNumber", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
