// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: player.proto

package mech.mania.engine.server.communication.player.model;

public final class PlayerProtos {
  private PlayerProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PlayerTurnOrBuilder extends
      // @@protoc_insertion_point(interface_extends:player_communication.PlayerTurn)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.game_state.GameState game_state = 1;</code>
     * @return Whether the gameState field is set.
     */
    boolean hasGameState();
    /**
     * <code>.game_state.GameState game_state = 1;</code>
     * @return The gameState.
     */
    mech.mania.engine.game.model.GameStateProtos.GameState getGameState();
    /**
     * <code>.game_state.GameState game_state = 1;</code>
     */
    mech.mania.engine.game.model.GameStateProtos.GameStateOrBuilder getGameStateOrBuilder();

    /**
     * <code>string test1 = 2;</code>
     * @return The test1.
     */
    java.lang.String getTest1();
    /**
     * <code>string test1 = 2;</code>
     * @return The bytes for test1.
     */
    com.google.protobuf.ByteString
        getTest1Bytes();

    /**
     * <code>int32 test2 = 3;</code>
     * @return The test2.
     */
    int getTest2();

    public mech.mania.engine.server.communication.player.model.PlayerProtos.PlayerTurn.TestCase getTestCase();
  }
  /**
   * <pre>
   * Proto sent from engine to player
   * </pre>
   *
   * Protobuf type {@code player_communication.PlayerTurn}
   */
  public static final class PlayerTurn extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:player_communication.PlayerTurn)
      PlayerTurnOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PlayerTurn.newBuilder() to construct.
    private PlayerTurn(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PlayerTurn() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new PlayerTurn();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PlayerTurn(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              mech.mania.engine.game.model.GameStateProtos.GameState.Builder subBuilder = null;
              if (gameState_ != null) {
                subBuilder = gameState_.toBuilder();
              }
              gameState_ = input.readMessage(mech.mania.engine.game.model.GameStateProtos.GameState.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(gameState_);
                gameState_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();
              testCase_ = 2;
              test_ = s;
              break;
            }
            case 24: {
              testCase_ = 3;
              test_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return mech.mania.engine.server.communication.player.model.PlayerProtos.internal_static_player_communication_PlayerTurn_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return mech.mania.engine.server.communication.player.model.PlayerProtos.internal_static_player_communication_PlayerTurn_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              mech.mania.engine.server.communication.player.model.PlayerProtos.PlayerTurn.class, mech.mania.engine.server.communication.player.model.PlayerProtos.PlayerTurn.Builder.class);
    }

    private int testCase_ = 0;
    private java.lang.Object test_;
    public enum TestCase
        implements com.google.protobuf.Internal.EnumLite,
            com.google.protobuf.AbstractMessage.InternalOneOfEnum {
      TEST1(2),
      TEST2(3),
      TEST_NOT_SET(0);
      private final int value;
      private TestCase(int value) {
        this.value = value;
      }
      /**
       * @param value The number of the enum to look for.
       * @return The enum associated with the given number.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static TestCase valueOf(int value) {
        return forNumber(value);
      }

      public static TestCase forNumber(int value) {
        switch (value) {
          case 2: return TEST1;
          case 3: return TEST2;
          case 0: return TEST_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public TestCase
    getTestCase() {
      return TestCase.forNumber(
          testCase_);
    }

    public static final int GAME_STATE_FIELD_NUMBER = 1;
    private mech.mania.engine.game.model.GameStateProtos.GameState gameState_;
    /**
     * <code>.game_state.GameState game_state = 1;</code>
     * @return Whether the gameState field is set.
     */
    @java.lang.Override
    public boolean hasGameState() {
      return gameState_ != null;
    }
    /**
     * <code>.game_state.GameState game_state = 1;</code>
     * @return The gameState.
     */
    @java.lang.Override
    public mech.mania.engine.game.model.GameStateProtos.GameState getGameState() {
      return gameState_ == null ? mech.mania.engine.game.model.GameStateProtos.GameState.getDefaultInstance() : gameState_;
    }
    /**
     * <code>.game_state.GameState game_state = 1;</code>
     */
    @java.lang.Override
    public mech.mania.engine.game.model.GameStateProtos.GameStateOrBuilder getGameStateOrBuilder() {
      return getGameState();
    }

    public static final int TEST1_FIELD_NUMBER = 2;
    /**
     * <code>string test1 = 2;</code>
     * @return The test1.
     */
    public java.lang.String getTest1() {
      java.lang.Object ref = "";
      if (testCase_ == 2) {
        ref = test_;
      }
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (testCase_ == 2) {
          test_ = s;
        }
        return s;
      }
    }
    /**
     * <code>string test1 = 2;</code>
     * @return The bytes for test1.
     */
    public com.google.protobuf.ByteString
        getTest1Bytes() {
      java.lang.Object ref = "";
      if (testCase_ == 2) {
        ref = test_;
      }
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        if (testCase_ == 2) {
          test_ = b;
        }
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TEST2_FIELD_NUMBER = 3;
    /**
     * <code>int32 test2 = 3;</code>
     * @return The test2.
     */
    @java.lang.Override
    public int getTest2() {
      if (testCase_ == 3) {
        return (java.lang.Integer) test_;
      }
      return 0;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (gameState_ != null) {
        output.writeMessage(1, getGameState());
      }
      if (testCase_ == 2) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, test_);
      }
      if (testCase_ == 3) {
        output.writeInt32(
            3, (int)((java.lang.Integer) test_));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (gameState_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getGameState());
      }
      if (testCase_ == 2) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, test_);
      }
      if (testCase_ == 3) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(
              3, (int)((java.lang.Integer) test_));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof mech.mania.engine.server.communication.player.model.PlayerProtos.PlayerTurn)) {
        return super.equals(obj);
      }
      mech.mania.engine.server.communication.player.model.PlayerProtos.PlayerTurn other = (mech.mania.engine.server.communication.player.model.PlayerProtos.PlayerTurn) obj;

      if (hasGameState() != other.hasGameState()) return false;
      if (hasGameState()) {
        if (!getGameState()
            .equals(other.getGameState())) return false;
      }
      if (!getTestCase().equals(other.getTestCase())) return false;
      switch (testCase_) {
        case 2:
          if (!getTest1()
              .equals(other.getTest1())) return false;
          break;
        case 3:
          if (getTest2()
              != other.getTest2()) return false;
          break;
        case 0:
        default:
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasGameState()) {
        hash = (37 * hash) + GAME_STATE_FIELD_NUMBER;
        hash = (53 * hash) + getGameState().hashCode();
      }
      switch (testCase_) {
        case 2:
          hash = (37 * hash) + TEST1_FIELD_NUMBER;
          hash = (53 * hash) + getTest1().hashCode();
          break;
        case 3:
          hash = (37 * hash) + TEST2_FIELD_NUMBER;
          hash = (53 * hash) + getTest2();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static mech.mania.engine.server.communication.player.model.PlayerProtos.PlayerTurn parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static mech.mania.engine.server.communication.player.model.PlayerProtos.PlayerTurn parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static mech.mania.engine.server.communication.player.model.PlayerProtos.PlayerTurn parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static mech.mania.engine.server.communication.player.model.PlayerProtos.PlayerTurn parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static mech.mania.engine.server.communication.player.model.PlayerProtos.PlayerTurn parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static mech.mania.engine.server.communication.player.model.PlayerProtos.PlayerTurn parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static mech.mania.engine.server.communication.player.model.PlayerProtos.PlayerTurn parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static mech.mania.engine.server.communication.player.model.PlayerProtos.PlayerTurn parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static mech.mania.engine.server.communication.player.model.PlayerProtos.PlayerTurn parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static mech.mania.engine.server.communication.player.model.PlayerProtos.PlayerTurn parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static mech.mania.engine.server.communication.player.model.PlayerProtos.PlayerTurn parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static mech.mania.engine.server.communication.player.model.PlayerProtos.PlayerTurn parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(mech.mania.engine.server.communication.player.model.PlayerProtos.PlayerTurn prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Proto sent from engine to player
     * </pre>
     *
     * Protobuf type {@code player_communication.PlayerTurn}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:player_communication.PlayerTurn)
        mech.mania.engine.server.communication.player.model.PlayerProtos.PlayerTurnOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return mech.mania.engine.server.communication.player.model.PlayerProtos.internal_static_player_communication_PlayerTurn_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return mech.mania.engine.server.communication.player.model.PlayerProtos.internal_static_player_communication_PlayerTurn_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                mech.mania.engine.server.communication.player.model.PlayerProtos.PlayerTurn.class, mech.mania.engine.server.communication.player.model.PlayerProtos.PlayerTurn.Builder.class);
      }

      // Construct using mech.mania.engine.server.communication.player.model.PlayerProtos.PlayerTurn.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (gameStateBuilder_ == null) {
          gameState_ = null;
        } else {
          gameState_ = null;
          gameStateBuilder_ = null;
        }
        testCase_ = 0;
        test_ = null;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return mech.mania.engine.server.communication.player.model.PlayerProtos.internal_static_player_communication_PlayerTurn_descriptor;
      }

      @java.lang.Override
      public mech.mania.engine.server.communication.player.model.PlayerProtos.PlayerTurn getDefaultInstanceForType() {
        return mech.mania.engine.server.communication.player.model.PlayerProtos.PlayerTurn.getDefaultInstance();
      }

      @java.lang.Override
      public mech.mania.engine.server.communication.player.model.PlayerProtos.PlayerTurn build() {
        mech.mania.engine.server.communication.player.model.PlayerProtos.PlayerTurn result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public mech.mania.engine.server.communication.player.model.PlayerProtos.PlayerTurn buildPartial() {
        mech.mania.engine.server.communication.player.model.PlayerProtos.PlayerTurn result = new mech.mania.engine.server.communication.player.model.PlayerProtos.PlayerTurn(this);
        if (gameStateBuilder_ == null) {
          result.gameState_ = gameState_;
        } else {
          result.gameState_ = gameStateBuilder_.build();
        }
        if (testCase_ == 2) {
          result.test_ = test_;
        }
        if (testCase_ == 3) {
          result.test_ = test_;
        }
        result.testCase_ = testCase_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof mech.mania.engine.server.communication.player.model.PlayerProtos.PlayerTurn) {
          return mergeFrom((mech.mania.engine.server.communication.player.model.PlayerProtos.PlayerTurn)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(mech.mania.engine.server.communication.player.model.PlayerProtos.PlayerTurn other) {
        if (other == mech.mania.engine.server.communication.player.model.PlayerProtos.PlayerTurn.getDefaultInstance()) return this;
        if (other.hasGameState()) {
          mergeGameState(other.getGameState());
        }
        switch (other.getTestCase()) {
          case TEST1: {
            testCase_ = 2;
            test_ = other.test_;
            onChanged();
            break;
          }
          case TEST2: {
            setTest2(other.getTest2());
            break;
          }
          case TEST_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        mech.mania.engine.server.communication.player.model.PlayerProtos.PlayerTurn parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (mech.mania.engine.server.communication.player.model.PlayerProtos.PlayerTurn) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int testCase_ = 0;
      private java.lang.Object test_;
      public TestCase
          getTestCase() {
        return TestCase.forNumber(
            testCase_);
      }

      public Builder clearTest() {
        testCase_ = 0;
        test_ = null;
        onChanged();
        return this;
      }


      private mech.mania.engine.game.model.GameStateProtos.GameState gameState_;
      private com.google.protobuf.SingleFieldBuilderV3<
          mech.mania.engine.game.model.GameStateProtos.GameState, mech.mania.engine.game.model.GameStateProtos.GameState.Builder, mech.mania.engine.game.model.GameStateProtos.GameStateOrBuilder> gameStateBuilder_;
      /**
       * <code>.game_state.GameState game_state = 1;</code>
       * @return Whether the gameState field is set.
       */
      public boolean hasGameState() {
        return gameStateBuilder_ != null || gameState_ != null;
      }
      /**
       * <code>.game_state.GameState game_state = 1;</code>
       * @return The gameState.
       */
      public mech.mania.engine.game.model.GameStateProtos.GameState getGameState() {
        if (gameStateBuilder_ == null) {
          return gameState_ == null ? mech.mania.engine.game.model.GameStateProtos.GameState.getDefaultInstance() : gameState_;
        } else {
          return gameStateBuilder_.getMessage();
        }
      }
      /**
       * <code>.game_state.GameState game_state = 1;</code>
       */
      public Builder setGameState(mech.mania.engine.game.model.GameStateProtos.GameState value) {
        if (gameStateBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          gameState_ = value;
          onChanged();
        } else {
          gameStateBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.game_state.GameState game_state = 1;</code>
       */
      public Builder setGameState(
          mech.mania.engine.game.model.GameStateProtos.GameState.Builder builderForValue) {
        if (gameStateBuilder_ == null) {
          gameState_ = builderForValue.build();
          onChanged();
        } else {
          gameStateBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.game_state.GameState game_state = 1;</code>
       */
      public Builder mergeGameState(mech.mania.engine.game.model.GameStateProtos.GameState value) {
        if (gameStateBuilder_ == null) {
          if (gameState_ != null) {
            gameState_ =
              mech.mania.engine.game.model.GameStateProtos.GameState.newBuilder(gameState_).mergeFrom(value).buildPartial();
          } else {
            gameState_ = value;
          }
          onChanged();
        } else {
          gameStateBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.game_state.GameState game_state = 1;</code>
       */
      public Builder clearGameState() {
        if (gameStateBuilder_ == null) {
          gameState_ = null;
          onChanged();
        } else {
          gameState_ = null;
          gameStateBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.game_state.GameState game_state = 1;</code>
       */
      public mech.mania.engine.game.model.GameStateProtos.GameState.Builder getGameStateBuilder() {
        
        onChanged();
        return getGameStateFieldBuilder().getBuilder();
      }
      /**
       * <code>.game_state.GameState game_state = 1;</code>
       */
      public mech.mania.engine.game.model.GameStateProtos.GameStateOrBuilder getGameStateOrBuilder() {
        if (gameStateBuilder_ != null) {
          return gameStateBuilder_.getMessageOrBuilder();
        } else {
          return gameState_ == null ?
              mech.mania.engine.game.model.GameStateProtos.GameState.getDefaultInstance() : gameState_;
        }
      }
      /**
       * <code>.game_state.GameState game_state = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          mech.mania.engine.game.model.GameStateProtos.GameState, mech.mania.engine.game.model.GameStateProtos.GameState.Builder, mech.mania.engine.game.model.GameStateProtos.GameStateOrBuilder> 
          getGameStateFieldBuilder() {
        if (gameStateBuilder_ == null) {
          gameStateBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              mech.mania.engine.game.model.GameStateProtos.GameState, mech.mania.engine.game.model.GameStateProtos.GameState.Builder, mech.mania.engine.game.model.GameStateProtos.GameStateOrBuilder>(
                  getGameState(),
                  getParentForChildren(),
                  isClean());
          gameState_ = null;
        }
        return gameStateBuilder_;
      }

      /**
       * <code>string test1 = 2;</code>
       * @return The test1.
       */
      @java.lang.Override
      public java.lang.String getTest1() {
        java.lang.Object ref = "";
        if (testCase_ == 2) {
          ref = test_;
        }
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (testCase_ == 2) {
            test_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string test1 = 2;</code>
       * @return The bytes for test1.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getTest1Bytes() {
        java.lang.Object ref = "";
        if (testCase_ == 2) {
          ref = test_;
        }
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          if (testCase_ == 2) {
            test_ = b;
          }
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string test1 = 2;</code>
       * @param value The test1 to set.
       * @return This builder for chaining.
       */
      public Builder setTest1(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  testCase_ = 2;
        test_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string test1 = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearTest1() {
        if (testCase_ == 2) {
          testCase_ = 0;
          test_ = null;
          onChanged();
        }
        return this;
      }
      /**
       * <code>string test1 = 2;</code>
       * @param value The bytes for test1 to set.
       * @return This builder for chaining.
       */
      public Builder setTest1Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        testCase_ = 2;
        test_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>int32 test2 = 3;</code>
       * @return The test2.
       */
      public int getTest2() {
        if (testCase_ == 3) {
          return (java.lang.Integer) test_;
        }
        return 0;
      }
      /**
       * <code>int32 test2 = 3;</code>
       * @param value The test2 to set.
       * @return This builder for chaining.
       */
      public Builder setTest2(int value) {
        testCase_ = 3;
        test_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 test2 = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearTest2() {
        if (testCase_ == 3) {
          testCase_ = 0;
          test_ = null;
          onChanged();
        }
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:player_communication.PlayerTurn)
    }

    // @@protoc_insertion_point(class_scope:player_communication.PlayerTurn)
    private static final mech.mania.engine.server.communication.player.model.PlayerProtos.PlayerTurn DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new mech.mania.engine.server.communication.player.model.PlayerProtos.PlayerTurn();
    }

    public static mech.mania.engine.server.communication.player.model.PlayerProtos.PlayerTurn getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PlayerTurn>
        PARSER = new com.google.protobuf.AbstractParser<PlayerTurn>() {
      @java.lang.Override
      public PlayerTurn parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PlayerTurn(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PlayerTurn> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PlayerTurn> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public mech.mania.engine.server.communication.player.model.PlayerProtos.PlayerTurn getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PlayerDecisionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:player_communication.PlayerDecision)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.DecisionType decisionType = 1;</code>
     * @return The enum numeric value on the wire for decisionType.
     */
    int getDecisionTypeValue();
    /**
     * <code>.DecisionType decisionType = 1;</code>
     * @return The decisionType.
     */
    Enums.DecisionType getDecisionType();

    /**
     * <pre>
     * For MOVE, ATTACK
     * </pre>
     *
     * <code>.character.Position targetPosition = 2;</code>
     * @return Whether the targetPosition field is set.
     */
    boolean hasTargetPosition();
    /**
     * <pre>
     * For MOVE, ATTACK
     * </pre>
     *
     * <code>.character.Position targetPosition = 2;</code>
     * @return The targetPosition.
     */
    mech.mania.engine.game.characters.CharacterProtos.Position getTargetPosition();
    /**
     * <pre>
     * For MOVE, ATTACK
     * </pre>
     *
     * <code>.character.Position targetPosition = 2;</code>
     */
    mech.mania.engine.game.characters.CharacterProtos.PositionOrBuilder getTargetPositionOrBuilder();

    /**
     * <pre>
     * For TRAVEL, DROP, EQUIP, PICKUP
     * </pre>
     *
     * <code>int32 index = 3;</code>
     * @return The index.
     */
    int getIndex();
  }
  /**
   * <pre>
   * Proto sent from player to engine
   * </pre>
   *
   * Protobuf type {@code player_communication.PlayerDecision}
   */
  public static final class PlayerDecision extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:player_communication.PlayerDecision)
      PlayerDecisionOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PlayerDecision.newBuilder() to construct.
    private PlayerDecision(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PlayerDecision() {
      decisionType_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new PlayerDecision();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PlayerDecision(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              decisionType_ = rawValue;
              break;
            }
            case 18: {
              mech.mania.engine.game.characters.CharacterProtos.Position.Builder subBuilder = null;
              if (targetPosition_ != null) {
                subBuilder = targetPosition_.toBuilder();
              }
              targetPosition_ = input.readMessage(mech.mania.engine.game.characters.CharacterProtos.Position.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(targetPosition_);
                targetPosition_ = subBuilder.buildPartial();
              }

              break;
            }
            case 24: {

              index_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return mech.mania.engine.server.communication.player.model.PlayerProtos.internal_static_player_communication_PlayerDecision_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return mech.mania.engine.server.communication.player.model.PlayerProtos.internal_static_player_communication_PlayerDecision_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              mech.mania.engine.server.communication.player.model.PlayerProtos.PlayerDecision.class, mech.mania.engine.server.communication.player.model.PlayerProtos.PlayerDecision.Builder.class);
    }

    public static final int DECISIONTYPE_FIELD_NUMBER = 1;
    private int decisionType_;
    /**
     * <code>.DecisionType decisionType = 1;</code>
     * @return The enum numeric value on the wire for decisionType.
     */
    @java.lang.Override public int getDecisionTypeValue() {
      return decisionType_;
    }
    /**
     * <code>.DecisionType decisionType = 1;</code>
     * @return The decisionType.
     */
    @java.lang.Override public Enums.DecisionType getDecisionType() {
      @SuppressWarnings("deprecation")
      Enums.DecisionType result = Enums.DecisionType.valueOf(decisionType_);
      return result == null ? Enums.DecisionType.UNRECOGNIZED : result;
    }

    public static final int TARGETPOSITION_FIELD_NUMBER = 2;
    private mech.mania.engine.game.characters.CharacterProtos.Position targetPosition_;
    /**
     * <pre>
     * For MOVE, ATTACK
     * </pre>
     *
     * <code>.character.Position targetPosition = 2;</code>
     * @return Whether the targetPosition field is set.
     */
    @java.lang.Override
    public boolean hasTargetPosition() {
      return targetPosition_ != null;
    }
    /**
     * <pre>
     * For MOVE, ATTACK
     * </pre>
     *
     * <code>.character.Position targetPosition = 2;</code>
     * @return The targetPosition.
     */
    @java.lang.Override
    public mech.mania.engine.game.characters.CharacterProtos.Position getTargetPosition() {
      return targetPosition_ == null ? mech.mania.engine.game.characters.CharacterProtos.Position.getDefaultInstance() : targetPosition_;
    }
    /**
     * <pre>
     * For MOVE, ATTACK
     * </pre>
     *
     * <code>.character.Position targetPosition = 2;</code>
     */
    @java.lang.Override
    public mech.mania.engine.game.characters.CharacterProtos.PositionOrBuilder getTargetPositionOrBuilder() {
      return getTargetPosition();
    }

    public static final int INDEX_FIELD_NUMBER = 3;
    private int index_;
    /**
     * <pre>
     * For TRAVEL, DROP, EQUIP, PICKUP
     * </pre>
     *
     * <code>int32 index = 3;</code>
     * @return The index.
     */
    @java.lang.Override
    public int getIndex() {
      return index_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (decisionType_ != Enums.DecisionType.NONE.getNumber()) {
        output.writeEnum(1, decisionType_);
      }
      if (targetPosition_ != null) {
        output.writeMessage(2, getTargetPosition());
      }
      if (index_ != 0) {
        output.writeInt32(3, index_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (decisionType_ != Enums.DecisionType.NONE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, decisionType_);
      }
      if (targetPosition_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getTargetPosition());
      }
      if (index_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, index_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof mech.mania.engine.server.communication.player.model.PlayerProtos.PlayerDecision)) {
        return super.equals(obj);
      }
      mech.mania.engine.server.communication.player.model.PlayerProtos.PlayerDecision other = (mech.mania.engine.server.communication.player.model.PlayerProtos.PlayerDecision) obj;

      if (decisionType_ != other.decisionType_) return false;
      if (hasTargetPosition() != other.hasTargetPosition()) return false;
      if (hasTargetPosition()) {
        if (!getTargetPosition()
            .equals(other.getTargetPosition())) return false;
      }
      if (getIndex()
          != other.getIndex()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DECISIONTYPE_FIELD_NUMBER;
      hash = (53 * hash) + decisionType_;
      if (hasTargetPosition()) {
        hash = (37 * hash) + TARGETPOSITION_FIELD_NUMBER;
        hash = (53 * hash) + getTargetPosition().hashCode();
      }
      hash = (37 * hash) + INDEX_FIELD_NUMBER;
      hash = (53 * hash) + getIndex();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static mech.mania.engine.server.communication.player.model.PlayerProtos.PlayerDecision parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static mech.mania.engine.server.communication.player.model.PlayerProtos.PlayerDecision parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static mech.mania.engine.server.communication.player.model.PlayerProtos.PlayerDecision parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static mech.mania.engine.server.communication.player.model.PlayerProtos.PlayerDecision parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static mech.mania.engine.server.communication.player.model.PlayerProtos.PlayerDecision parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static mech.mania.engine.server.communication.player.model.PlayerProtos.PlayerDecision parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static mech.mania.engine.server.communication.player.model.PlayerProtos.PlayerDecision parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static mech.mania.engine.server.communication.player.model.PlayerProtos.PlayerDecision parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static mech.mania.engine.server.communication.player.model.PlayerProtos.PlayerDecision parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static mech.mania.engine.server.communication.player.model.PlayerProtos.PlayerDecision parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static mech.mania.engine.server.communication.player.model.PlayerProtos.PlayerDecision parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static mech.mania.engine.server.communication.player.model.PlayerProtos.PlayerDecision parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(mech.mania.engine.server.communication.player.model.PlayerProtos.PlayerDecision prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Proto sent from player to engine
     * </pre>
     *
     * Protobuf type {@code player_communication.PlayerDecision}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:player_communication.PlayerDecision)
        mech.mania.engine.server.communication.player.model.PlayerProtos.PlayerDecisionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return mech.mania.engine.server.communication.player.model.PlayerProtos.internal_static_player_communication_PlayerDecision_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return mech.mania.engine.server.communication.player.model.PlayerProtos.internal_static_player_communication_PlayerDecision_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                mech.mania.engine.server.communication.player.model.PlayerProtos.PlayerDecision.class, mech.mania.engine.server.communication.player.model.PlayerProtos.PlayerDecision.Builder.class);
      }

      // Construct using mech.mania.engine.server.communication.player.model.PlayerProtos.PlayerDecision.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        decisionType_ = 0;

        if (targetPositionBuilder_ == null) {
          targetPosition_ = null;
        } else {
          targetPosition_ = null;
          targetPositionBuilder_ = null;
        }
        index_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return mech.mania.engine.server.communication.player.model.PlayerProtos.internal_static_player_communication_PlayerDecision_descriptor;
      }

      @java.lang.Override
      public mech.mania.engine.server.communication.player.model.PlayerProtos.PlayerDecision getDefaultInstanceForType() {
        return mech.mania.engine.server.communication.player.model.PlayerProtos.PlayerDecision.getDefaultInstance();
      }

      @java.lang.Override
      public mech.mania.engine.server.communication.player.model.PlayerProtos.PlayerDecision build() {
        mech.mania.engine.server.communication.player.model.PlayerProtos.PlayerDecision result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public mech.mania.engine.server.communication.player.model.PlayerProtos.PlayerDecision buildPartial() {
        mech.mania.engine.server.communication.player.model.PlayerProtos.PlayerDecision result = new mech.mania.engine.server.communication.player.model.PlayerProtos.PlayerDecision(this);
        result.decisionType_ = decisionType_;
        if (targetPositionBuilder_ == null) {
          result.targetPosition_ = targetPosition_;
        } else {
          result.targetPosition_ = targetPositionBuilder_.build();
        }
        result.index_ = index_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof mech.mania.engine.server.communication.player.model.PlayerProtos.PlayerDecision) {
          return mergeFrom((mech.mania.engine.server.communication.player.model.PlayerProtos.PlayerDecision)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(mech.mania.engine.server.communication.player.model.PlayerProtos.PlayerDecision other) {
        if (other == mech.mania.engine.server.communication.player.model.PlayerProtos.PlayerDecision.getDefaultInstance()) return this;
        if (other.decisionType_ != 0) {
          setDecisionTypeValue(other.getDecisionTypeValue());
        }
        if (other.hasTargetPosition()) {
          mergeTargetPosition(other.getTargetPosition());
        }
        if (other.getIndex() != 0) {
          setIndex(other.getIndex());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        mech.mania.engine.server.communication.player.model.PlayerProtos.PlayerDecision parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (mech.mania.engine.server.communication.player.model.PlayerProtos.PlayerDecision) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int decisionType_ = 0;
      /**
       * <code>.DecisionType decisionType = 1;</code>
       * @return The enum numeric value on the wire for decisionType.
       */
      @java.lang.Override public int getDecisionTypeValue() {
        return decisionType_;
      }
      /**
       * <code>.DecisionType decisionType = 1;</code>
       * @param value The enum numeric value on the wire for decisionType to set.
       * @return This builder for chaining.
       */
      public Builder setDecisionTypeValue(int value) {
        
        decisionType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.DecisionType decisionType = 1;</code>
       * @return The decisionType.
       */
      @java.lang.Override
      public Enums.DecisionType getDecisionType() {
        @SuppressWarnings("deprecation")
        Enums.DecisionType result = Enums.DecisionType.valueOf(decisionType_);
        return result == null ? Enums.DecisionType.UNRECOGNIZED : result;
      }
      /**
       * <code>.DecisionType decisionType = 1;</code>
       * @param value The decisionType to set.
       * @return This builder for chaining.
       */
      public Builder setDecisionType(Enums.DecisionType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        decisionType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.DecisionType decisionType = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearDecisionType() {
        
        decisionType_ = 0;
        onChanged();
        return this;
      }

      private mech.mania.engine.game.characters.CharacterProtos.Position targetPosition_;
      private com.google.protobuf.SingleFieldBuilderV3<
          mech.mania.engine.game.characters.CharacterProtos.Position, mech.mania.engine.game.characters.CharacterProtos.Position.Builder, mech.mania.engine.game.characters.CharacterProtos.PositionOrBuilder> targetPositionBuilder_;
      /**
       * <pre>
       * For MOVE, ATTACK
       * </pre>
       *
       * <code>.character.Position targetPosition = 2;</code>
       * @return Whether the targetPosition field is set.
       */
      public boolean hasTargetPosition() {
        return targetPositionBuilder_ != null || targetPosition_ != null;
      }
      /**
       * <pre>
       * For MOVE, ATTACK
       * </pre>
       *
       * <code>.character.Position targetPosition = 2;</code>
       * @return The targetPosition.
       */
      public mech.mania.engine.game.characters.CharacterProtos.Position getTargetPosition() {
        if (targetPositionBuilder_ == null) {
          return targetPosition_ == null ? mech.mania.engine.game.characters.CharacterProtos.Position.getDefaultInstance() : targetPosition_;
        } else {
          return targetPositionBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * For MOVE, ATTACK
       * </pre>
       *
       * <code>.character.Position targetPosition = 2;</code>
       */
      public Builder setTargetPosition(mech.mania.engine.game.characters.CharacterProtos.Position value) {
        if (targetPositionBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          targetPosition_ = value;
          onChanged();
        } else {
          targetPositionBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       * For MOVE, ATTACK
       * </pre>
       *
       * <code>.character.Position targetPosition = 2;</code>
       */
      public Builder setTargetPosition(
          mech.mania.engine.game.characters.CharacterProtos.Position.Builder builderForValue) {
        if (targetPositionBuilder_ == null) {
          targetPosition_ = builderForValue.build();
          onChanged();
        } else {
          targetPositionBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       * For MOVE, ATTACK
       * </pre>
       *
       * <code>.character.Position targetPosition = 2;</code>
       */
      public Builder mergeTargetPosition(mech.mania.engine.game.characters.CharacterProtos.Position value) {
        if (targetPositionBuilder_ == null) {
          if (targetPosition_ != null) {
            targetPosition_ =
              mech.mania.engine.game.characters.CharacterProtos.Position.newBuilder(targetPosition_).mergeFrom(value).buildPartial();
          } else {
            targetPosition_ = value;
          }
          onChanged();
        } else {
          targetPositionBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       * For MOVE, ATTACK
       * </pre>
       *
       * <code>.character.Position targetPosition = 2;</code>
       */
      public Builder clearTargetPosition() {
        if (targetPositionBuilder_ == null) {
          targetPosition_ = null;
          onChanged();
        } else {
          targetPosition_ = null;
          targetPositionBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       * For MOVE, ATTACK
       * </pre>
       *
       * <code>.character.Position targetPosition = 2;</code>
       */
      public mech.mania.engine.game.characters.CharacterProtos.Position.Builder getTargetPositionBuilder() {
        
        onChanged();
        return getTargetPositionFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * For MOVE, ATTACK
       * </pre>
       *
       * <code>.character.Position targetPosition = 2;</code>
       */
      public mech.mania.engine.game.characters.CharacterProtos.PositionOrBuilder getTargetPositionOrBuilder() {
        if (targetPositionBuilder_ != null) {
          return targetPositionBuilder_.getMessageOrBuilder();
        } else {
          return targetPosition_ == null ?
              mech.mania.engine.game.characters.CharacterProtos.Position.getDefaultInstance() : targetPosition_;
        }
      }
      /**
       * <pre>
       * For MOVE, ATTACK
       * </pre>
       *
       * <code>.character.Position targetPosition = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          mech.mania.engine.game.characters.CharacterProtos.Position, mech.mania.engine.game.characters.CharacterProtos.Position.Builder, mech.mania.engine.game.characters.CharacterProtos.PositionOrBuilder> 
          getTargetPositionFieldBuilder() {
        if (targetPositionBuilder_ == null) {
          targetPositionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              mech.mania.engine.game.characters.CharacterProtos.Position, mech.mania.engine.game.characters.CharacterProtos.Position.Builder, mech.mania.engine.game.characters.CharacterProtos.PositionOrBuilder>(
                  getTargetPosition(),
                  getParentForChildren(),
                  isClean());
          targetPosition_ = null;
        }
        return targetPositionBuilder_;
      }

      private int index_ ;
      /**
       * <pre>
       * For TRAVEL, DROP, EQUIP, PICKUP
       * </pre>
       *
       * <code>int32 index = 3;</code>
       * @return The index.
       */
      @java.lang.Override
      public int getIndex() {
        return index_;
      }
      /**
       * <pre>
       * For TRAVEL, DROP, EQUIP, PICKUP
       * </pre>
       *
       * <code>int32 index = 3;</code>
       * @param value The index to set.
       * @return This builder for chaining.
       */
      public Builder setIndex(int value) {
        
        index_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * For TRAVEL, DROP, EQUIP, PICKUP
       * </pre>
       *
       * <code>int32 index = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearIndex() {
        
        index_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:player_communication.PlayerDecision)
    }

    // @@protoc_insertion_point(class_scope:player_communication.PlayerDecision)
    private static final mech.mania.engine.server.communication.player.model.PlayerProtos.PlayerDecision DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new mech.mania.engine.server.communication.player.model.PlayerProtos.PlayerDecision();
    }

    public static mech.mania.engine.server.communication.player.model.PlayerProtos.PlayerDecision getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PlayerDecision>
        PARSER = new com.google.protobuf.AbstractParser<PlayerDecision>() {
      @java.lang.Override
      public PlayerDecision parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PlayerDecision(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PlayerDecision> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PlayerDecision> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public mech.mania.engine.server.communication.player.model.PlayerProtos.PlayerDecision getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_player_communication_PlayerTurn_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_player_communication_PlayerTurn_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_player_communication_PlayerDecision_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_player_communication_PlayerDecision_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014player.proto\022\024player_communication\032\013en" +
      "ums.proto\032\020game_state.proto\032\017character.p" +
      "roto\"a\n\nPlayerTurn\022)\n\ngame_state\030\001 \001(\0132\025" +
      ".game_state.GameState\022\017\n\005test1\030\002 \001(\tH\000\022\017" +
      "\n\005test2\030\003 \001(\005H\000B\006\n\004test\"q\n\016PlayerDecisio" +
      "n\022#\n\014decisionType\030\001 \001(\0162\r.DecisionType\022+" +
      "\n\016targetPosition\030\002 \001(\0132\023.character.Posit" +
      "ion\022\r\n\005index\030\003 \001(\005BT\n3mech.mania.engine." +
      "server.communication.player.modelB\014Playe" +
      "rProtos\252\002\016MM26.IO.Modelsb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          Enums.getDescriptor(),
          mech.mania.engine.game.model.GameStateProtos.getDescriptor(),
          mech.mania.engine.game.characters.CharacterProtos.getDescriptor(),
        });
    internal_static_player_communication_PlayerTurn_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_player_communication_PlayerTurn_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_player_communication_PlayerTurn_descriptor,
        new java.lang.String[] { "GameState", "Test1", "Test2", "Test", });
    internal_static_player_communication_PlayerDecision_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_player_communication_PlayerDecision_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_player_communication_PlayerDecision_descriptor,
        new java.lang.String[] { "DecisionType", "TargetPosition", "Index", });
    Enums.getDescriptor();
    mech.mania.engine.game.model.GameStateProtos.getDescriptor();
    mech.mania.engine.game.characters.CharacterProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
