// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: infra.proto

package mech.mania.engine.domain.model;

public final class InfraProtos {
  private InfraProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface InfraPlayerOrBuilder extends
      // @@protoc_insertion_point(interface_extends:infra.InfraPlayer)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string player_name = 1;</code>
     * @return The playerName.
     */
    java.lang.String getPlayerName();
    /**
     * <code>string player_name = 1;</code>
     * @return The bytes for playerName.
     */
    com.google.protobuf.ByteString
        getPlayerNameBytes();

    /**
     * <code>string player_ip = 2;</code>
     * @return The playerIp.
     */
    java.lang.String getPlayerIp();
    /**
     * <code>string player_ip = 2;</code>
     * @return The bytes for playerIp.
     */
    com.google.protobuf.ByteString
        getPlayerIpBytes();
  }
  /**
   * Protobuf type {@code infra.InfraPlayer}
   */
  public static final class InfraPlayer extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:infra.InfraPlayer)
      InfraPlayerOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use InfraPlayer.newBuilder() to construct.
    private InfraPlayer(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private InfraPlayer() {
      playerName_ = "";
      playerIp_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new InfraPlayer();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private InfraPlayer(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              playerName_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              playerIp_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return mech.mania.engine.domain.model.InfraProtos.internal_static_infra_InfraPlayer_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return mech.mania.engine.domain.model.InfraProtos.internal_static_infra_InfraPlayer_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              mech.mania.engine.domain.model.InfraProtos.InfraPlayer.class, mech.mania.engine.domain.model.InfraProtos.InfraPlayer.Builder.class);
    }

    public static final int PLAYER_NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object playerName_;
    /**
     * <code>string player_name = 1;</code>
     * @return The playerName.
     */
    @java.lang.Override
    public java.lang.String getPlayerName() {
      java.lang.Object ref = playerName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        playerName_ = s;
        return s;
      }
    }
    /**
     * <code>string player_name = 1;</code>
     * @return The bytes for playerName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPlayerNameBytes() {
      java.lang.Object ref = playerName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        playerName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PLAYER_IP_FIELD_NUMBER = 2;
    private volatile java.lang.Object playerIp_;
    /**
     * <code>string player_ip = 2;</code>
     * @return The playerIp.
     */
    @java.lang.Override
    public java.lang.String getPlayerIp() {
      java.lang.Object ref = playerIp_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        playerIp_ = s;
        return s;
      }
    }
    /**
     * <code>string player_ip = 2;</code>
     * @return The bytes for playerIp.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPlayerIpBytes() {
      java.lang.Object ref = playerIp_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        playerIp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getPlayerNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, playerName_);
      }
      if (!getPlayerIpBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, playerIp_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getPlayerNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, playerName_);
      }
      if (!getPlayerIpBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, playerIp_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof mech.mania.engine.domain.model.InfraProtos.InfraPlayer)) {
        return super.equals(obj);
      }
      mech.mania.engine.domain.model.InfraProtos.InfraPlayer other = (mech.mania.engine.domain.model.InfraProtos.InfraPlayer) obj;

      if (!getPlayerName()
          .equals(other.getPlayerName())) return false;
      if (!getPlayerIp()
          .equals(other.getPlayerIp())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PLAYER_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getPlayerName().hashCode();
      hash = (37 * hash) + PLAYER_IP_FIELD_NUMBER;
      hash = (53 * hash) + getPlayerIp().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static mech.mania.engine.domain.model.InfraProtos.InfraPlayer parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static mech.mania.engine.domain.model.InfraProtos.InfraPlayer parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static mech.mania.engine.domain.model.InfraProtos.InfraPlayer parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static mech.mania.engine.domain.model.InfraProtos.InfraPlayer parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static mech.mania.engine.domain.model.InfraProtos.InfraPlayer parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static mech.mania.engine.domain.model.InfraProtos.InfraPlayer parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static mech.mania.engine.domain.model.InfraProtos.InfraPlayer parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static mech.mania.engine.domain.model.InfraProtos.InfraPlayer parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static mech.mania.engine.domain.model.InfraProtos.InfraPlayer parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static mech.mania.engine.domain.model.InfraProtos.InfraPlayer parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static mech.mania.engine.domain.model.InfraProtos.InfraPlayer parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static mech.mania.engine.domain.model.InfraProtos.InfraPlayer parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(mech.mania.engine.domain.model.InfraProtos.InfraPlayer prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code infra.InfraPlayer}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:infra.InfraPlayer)
        mech.mania.engine.domain.model.InfraProtos.InfraPlayerOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return mech.mania.engine.domain.model.InfraProtos.internal_static_infra_InfraPlayer_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return mech.mania.engine.domain.model.InfraProtos.internal_static_infra_InfraPlayer_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                mech.mania.engine.domain.model.InfraProtos.InfraPlayer.class, mech.mania.engine.domain.model.InfraProtos.InfraPlayer.Builder.class);
      }

      // Construct using mech.mania.engine.domain.model.InfraProtos.InfraPlayer.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        playerName_ = "";

        playerIp_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return mech.mania.engine.domain.model.InfraProtos.internal_static_infra_InfraPlayer_descriptor;
      }

      @java.lang.Override
      public mech.mania.engine.domain.model.InfraProtos.InfraPlayer getDefaultInstanceForType() {
        return mech.mania.engine.domain.model.InfraProtos.InfraPlayer.getDefaultInstance();
      }

      @java.lang.Override
      public mech.mania.engine.domain.model.InfraProtos.InfraPlayer build() {
        mech.mania.engine.domain.model.InfraProtos.InfraPlayer result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public mech.mania.engine.domain.model.InfraProtos.InfraPlayer buildPartial() {
        mech.mania.engine.domain.model.InfraProtos.InfraPlayer result = new mech.mania.engine.domain.model.InfraProtos.InfraPlayer(this);
        result.playerName_ = playerName_;
        result.playerIp_ = playerIp_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof mech.mania.engine.domain.model.InfraProtos.InfraPlayer) {
          return mergeFrom((mech.mania.engine.domain.model.InfraProtos.InfraPlayer)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(mech.mania.engine.domain.model.InfraProtos.InfraPlayer other) {
        if (other == mech.mania.engine.domain.model.InfraProtos.InfraPlayer.getDefaultInstance()) return this;
        if (!other.getPlayerName().isEmpty()) {
          playerName_ = other.playerName_;
          onChanged();
        }
        if (!other.getPlayerIp().isEmpty()) {
          playerIp_ = other.playerIp_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        mech.mania.engine.domain.model.InfraProtos.InfraPlayer parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (mech.mania.engine.domain.model.InfraProtos.InfraPlayer) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object playerName_ = "";
      /**
       * <code>string player_name = 1;</code>
       * @return The playerName.
       */
      public java.lang.String getPlayerName() {
        java.lang.Object ref = playerName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          playerName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string player_name = 1;</code>
       * @return The bytes for playerName.
       */
      public com.google.protobuf.ByteString
          getPlayerNameBytes() {
        java.lang.Object ref = playerName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          playerName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string player_name = 1;</code>
       * @param value The playerName to set.
       * @return This builder for chaining.
       */
      public Builder setPlayerName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        playerName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string player_name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearPlayerName() {
        
        playerName_ = getDefaultInstance().getPlayerName();
        onChanged();
        return this;
      }
      /**
       * <code>string player_name = 1;</code>
       * @param value The bytes for playerName to set.
       * @return This builder for chaining.
       */
      public Builder setPlayerNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        playerName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object playerIp_ = "";
      /**
       * <code>string player_ip = 2;</code>
       * @return The playerIp.
       */
      public java.lang.String getPlayerIp() {
        java.lang.Object ref = playerIp_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          playerIp_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string player_ip = 2;</code>
       * @return The bytes for playerIp.
       */
      public com.google.protobuf.ByteString
          getPlayerIpBytes() {
        java.lang.Object ref = playerIp_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          playerIp_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string player_ip = 2;</code>
       * @param value The playerIp to set.
       * @return This builder for chaining.
       */
      public Builder setPlayerIp(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        playerIp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string player_ip = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearPlayerIp() {
        
        playerIp_ = getDefaultInstance().getPlayerIp();
        onChanged();
        return this;
      }
      /**
       * <code>string player_ip = 2;</code>
       * @param value The bytes for playerIp to set.
       * @return This builder for chaining.
       */
      public Builder setPlayerIpBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        playerIp_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:infra.InfraPlayer)
    }

    // @@protoc_insertion_point(class_scope:infra.InfraPlayer)
    private static final mech.mania.engine.domain.model.InfraProtos.InfraPlayer DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new mech.mania.engine.domain.model.InfraProtos.InfraPlayer();
    }

    public static mech.mania.engine.domain.model.InfraProtos.InfraPlayer getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<InfraPlayer>
        PARSER = new com.google.protobuf.AbstractParser<InfraPlayer>() {
      @java.lang.Override
      public InfraPlayer parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new InfraPlayer(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<InfraPlayer> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<InfraPlayer> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public mech.mania.engine.domain.model.InfraProtos.InfraPlayer getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface InfraVisualizerOrBuilder extends
      // @@protoc_insertion_point(interface_extends:infra.InfraVisualizer)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string visualizer_connect_url = 1;</code>
     * @return The visualizerConnectUrl.
     */
    java.lang.String getVisualizerConnectUrl();
    /**
     * <code>string visualizer_connect_url = 1;</code>
     * @return The bytes for visualizerConnectUrl.
     */
    com.google.protobuf.ByteString
        getVisualizerConnectUrlBytes();
  }
  /**
   * Protobuf type {@code infra.InfraVisualizer}
   */
  public static final class InfraVisualizer extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:infra.InfraVisualizer)
      InfraVisualizerOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use InfraVisualizer.newBuilder() to construct.
    private InfraVisualizer(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private InfraVisualizer() {
      visualizerConnectUrl_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new InfraVisualizer();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private InfraVisualizer(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              visualizerConnectUrl_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return mech.mania.engine.domain.model.InfraProtos.internal_static_infra_InfraVisualizer_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return mech.mania.engine.domain.model.InfraProtos.internal_static_infra_InfraVisualizer_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              mech.mania.engine.domain.model.InfraProtos.InfraVisualizer.class, mech.mania.engine.domain.model.InfraProtos.InfraVisualizer.Builder.class);
    }

    public static final int VISUALIZER_CONNECT_URL_FIELD_NUMBER = 1;
    private volatile java.lang.Object visualizerConnectUrl_;
    /**
     * <code>string visualizer_connect_url = 1;</code>
     * @return The visualizerConnectUrl.
     */
    @java.lang.Override
    public java.lang.String getVisualizerConnectUrl() {
      java.lang.Object ref = visualizerConnectUrl_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        visualizerConnectUrl_ = s;
        return s;
      }
    }
    /**
     * <code>string visualizer_connect_url = 1;</code>
     * @return The bytes for visualizerConnectUrl.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getVisualizerConnectUrlBytes() {
      java.lang.Object ref = visualizerConnectUrl_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        visualizerConnectUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getVisualizerConnectUrlBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, visualizerConnectUrl_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getVisualizerConnectUrlBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, visualizerConnectUrl_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof mech.mania.engine.domain.model.InfraProtos.InfraVisualizer)) {
        return super.equals(obj);
      }
      mech.mania.engine.domain.model.InfraProtos.InfraVisualizer other = (mech.mania.engine.domain.model.InfraProtos.InfraVisualizer) obj;

      if (!getVisualizerConnectUrl()
          .equals(other.getVisualizerConnectUrl())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + VISUALIZER_CONNECT_URL_FIELD_NUMBER;
      hash = (53 * hash) + getVisualizerConnectUrl().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static mech.mania.engine.domain.model.InfraProtos.InfraVisualizer parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static mech.mania.engine.domain.model.InfraProtos.InfraVisualizer parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static mech.mania.engine.domain.model.InfraProtos.InfraVisualizer parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static mech.mania.engine.domain.model.InfraProtos.InfraVisualizer parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static mech.mania.engine.domain.model.InfraProtos.InfraVisualizer parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static mech.mania.engine.domain.model.InfraProtos.InfraVisualizer parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static mech.mania.engine.domain.model.InfraProtos.InfraVisualizer parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static mech.mania.engine.domain.model.InfraProtos.InfraVisualizer parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static mech.mania.engine.domain.model.InfraProtos.InfraVisualizer parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static mech.mania.engine.domain.model.InfraProtos.InfraVisualizer parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static mech.mania.engine.domain.model.InfraProtos.InfraVisualizer parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static mech.mania.engine.domain.model.InfraProtos.InfraVisualizer parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(mech.mania.engine.domain.model.InfraProtos.InfraVisualizer prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code infra.InfraVisualizer}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:infra.InfraVisualizer)
        mech.mania.engine.domain.model.InfraProtos.InfraVisualizerOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return mech.mania.engine.domain.model.InfraProtos.internal_static_infra_InfraVisualizer_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return mech.mania.engine.domain.model.InfraProtos.internal_static_infra_InfraVisualizer_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                mech.mania.engine.domain.model.InfraProtos.InfraVisualizer.class, mech.mania.engine.domain.model.InfraProtos.InfraVisualizer.Builder.class);
      }

      // Construct using mech.mania.engine.domain.model.InfraProtos.InfraVisualizer.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        visualizerConnectUrl_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return mech.mania.engine.domain.model.InfraProtos.internal_static_infra_InfraVisualizer_descriptor;
      }

      @java.lang.Override
      public mech.mania.engine.domain.model.InfraProtos.InfraVisualizer getDefaultInstanceForType() {
        return mech.mania.engine.domain.model.InfraProtos.InfraVisualizer.getDefaultInstance();
      }

      @java.lang.Override
      public mech.mania.engine.domain.model.InfraProtos.InfraVisualizer build() {
        mech.mania.engine.domain.model.InfraProtos.InfraVisualizer result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public mech.mania.engine.domain.model.InfraProtos.InfraVisualizer buildPartial() {
        mech.mania.engine.domain.model.InfraProtos.InfraVisualizer result = new mech.mania.engine.domain.model.InfraProtos.InfraVisualizer(this);
        result.visualizerConnectUrl_ = visualizerConnectUrl_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof mech.mania.engine.domain.model.InfraProtos.InfraVisualizer) {
          return mergeFrom((mech.mania.engine.domain.model.InfraProtos.InfraVisualizer)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(mech.mania.engine.domain.model.InfraProtos.InfraVisualizer other) {
        if (other == mech.mania.engine.domain.model.InfraProtos.InfraVisualizer.getDefaultInstance()) return this;
        if (!other.getVisualizerConnectUrl().isEmpty()) {
          visualizerConnectUrl_ = other.visualizerConnectUrl_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        mech.mania.engine.domain.model.InfraProtos.InfraVisualizer parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (mech.mania.engine.domain.model.InfraProtos.InfraVisualizer) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object visualizerConnectUrl_ = "";
      /**
       * <code>string visualizer_connect_url = 1;</code>
       * @return The visualizerConnectUrl.
       */
      public java.lang.String getVisualizerConnectUrl() {
        java.lang.Object ref = visualizerConnectUrl_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          visualizerConnectUrl_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string visualizer_connect_url = 1;</code>
       * @return The bytes for visualizerConnectUrl.
       */
      public com.google.protobuf.ByteString
          getVisualizerConnectUrlBytes() {
        java.lang.Object ref = visualizerConnectUrl_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          visualizerConnectUrl_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string visualizer_connect_url = 1;</code>
       * @param value The visualizerConnectUrl to set.
       * @return This builder for chaining.
       */
      public Builder setVisualizerConnectUrl(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        visualizerConnectUrl_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string visualizer_connect_url = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearVisualizerConnectUrl() {
        
        visualizerConnectUrl_ = getDefaultInstance().getVisualizerConnectUrl();
        onChanged();
        return this;
      }
      /**
       * <code>string visualizer_connect_url = 1;</code>
       * @param value The bytes for visualizerConnectUrl to set.
       * @return This builder for chaining.
       */
      public Builder setVisualizerConnectUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        visualizerConnectUrl_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:infra.InfraVisualizer)
    }

    // @@protoc_insertion_point(class_scope:infra.InfraVisualizer)
    private static final mech.mania.engine.domain.model.InfraProtos.InfraVisualizer DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new mech.mania.engine.domain.model.InfraProtos.InfraVisualizer();
    }

    public static mech.mania.engine.domain.model.InfraProtos.InfraVisualizer getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<InfraVisualizer>
        PARSER = new com.google.protobuf.AbstractParser<InfraVisualizer>() {
      @java.lang.Override
      public InfraVisualizer parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new InfraVisualizer(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<InfraVisualizer> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<InfraVisualizer> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public mech.mania.engine.domain.model.InfraProtos.InfraVisualizer getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface InfraStatusOrBuilder extends
      // @@protoc_insertion_point(interface_extends:infra.InfraStatus)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 status = 1;</code>
     * @return The status.
     */
    int getStatus();

    /**
     * <code>string message = 2;</code>
     * @return The message.
     */
    java.lang.String getMessage();
    /**
     * <code>string message = 2;</code>
     * @return The bytes for message.
     */
    com.google.protobuf.ByteString
        getMessageBytes();
  }
  /**
   * Protobuf type {@code infra.InfraStatus}
   */
  public static final class InfraStatus extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:infra.InfraStatus)
      InfraStatusOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use InfraStatus.newBuilder() to construct.
    private InfraStatus(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private InfraStatus() {
      message_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new InfraStatus();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private InfraStatus(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              status_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              message_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return mech.mania.engine.domain.model.InfraProtos.internal_static_infra_InfraStatus_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return mech.mania.engine.domain.model.InfraProtos.internal_static_infra_InfraStatus_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              mech.mania.engine.domain.model.InfraProtos.InfraStatus.class, mech.mania.engine.domain.model.InfraProtos.InfraStatus.Builder.class);
    }

    public static final int STATUS_FIELD_NUMBER = 1;
    private int status_;
    /**
     * <code>int32 status = 1;</code>
     * @return The status.
     */
    @java.lang.Override
    public int getStatus() {
      return status_;
    }

    public static final int MESSAGE_FIELD_NUMBER = 2;
    private volatile java.lang.Object message_;
    /**
     * <code>string message = 2;</code>
     * @return The message.
     */
    @java.lang.Override
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      }
    }
    /**
     * <code>string message = 2;</code>
     * @return The bytes for message.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (status_ != 0) {
        output.writeInt32(1, status_);
      }
      if (!getMessageBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, message_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (status_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, status_);
      }
      if (!getMessageBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, message_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof mech.mania.engine.domain.model.InfraProtos.InfraStatus)) {
        return super.equals(obj);
      }
      mech.mania.engine.domain.model.InfraProtos.InfraStatus other = (mech.mania.engine.domain.model.InfraProtos.InfraStatus) obj;

      if (getStatus()
          != other.getStatus()) return false;
      if (!getMessage()
          .equals(other.getMessage())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + getStatus();
      hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getMessage().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static mech.mania.engine.domain.model.InfraProtos.InfraStatus parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static mech.mania.engine.domain.model.InfraProtos.InfraStatus parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static mech.mania.engine.domain.model.InfraProtos.InfraStatus parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static mech.mania.engine.domain.model.InfraProtos.InfraStatus parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static mech.mania.engine.domain.model.InfraProtos.InfraStatus parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static mech.mania.engine.domain.model.InfraProtos.InfraStatus parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static mech.mania.engine.domain.model.InfraProtos.InfraStatus parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static mech.mania.engine.domain.model.InfraProtos.InfraStatus parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static mech.mania.engine.domain.model.InfraProtos.InfraStatus parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static mech.mania.engine.domain.model.InfraProtos.InfraStatus parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static mech.mania.engine.domain.model.InfraProtos.InfraStatus parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static mech.mania.engine.domain.model.InfraProtos.InfraStatus parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(mech.mania.engine.domain.model.InfraProtos.InfraStatus prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code infra.InfraStatus}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:infra.InfraStatus)
        mech.mania.engine.domain.model.InfraProtos.InfraStatusOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return mech.mania.engine.domain.model.InfraProtos.internal_static_infra_InfraStatus_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return mech.mania.engine.domain.model.InfraProtos.internal_static_infra_InfraStatus_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                mech.mania.engine.domain.model.InfraProtos.InfraStatus.class, mech.mania.engine.domain.model.InfraProtos.InfraStatus.Builder.class);
      }

      // Construct using mech.mania.engine.domain.model.InfraProtos.InfraStatus.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        status_ = 0;

        message_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return mech.mania.engine.domain.model.InfraProtos.internal_static_infra_InfraStatus_descriptor;
      }

      @java.lang.Override
      public mech.mania.engine.domain.model.InfraProtos.InfraStatus getDefaultInstanceForType() {
        return mech.mania.engine.domain.model.InfraProtos.InfraStatus.getDefaultInstance();
      }

      @java.lang.Override
      public mech.mania.engine.domain.model.InfraProtos.InfraStatus build() {
        mech.mania.engine.domain.model.InfraProtos.InfraStatus result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public mech.mania.engine.domain.model.InfraProtos.InfraStatus buildPartial() {
        mech.mania.engine.domain.model.InfraProtos.InfraStatus result = new mech.mania.engine.domain.model.InfraProtos.InfraStatus(this);
        result.status_ = status_;
        result.message_ = message_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof mech.mania.engine.domain.model.InfraProtos.InfraStatus) {
          return mergeFrom((mech.mania.engine.domain.model.InfraProtos.InfraStatus)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(mech.mania.engine.domain.model.InfraProtos.InfraStatus other) {
        if (other == mech.mania.engine.domain.model.InfraProtos.InfraStatus.getDefaultInstance()) return this;
        if (other.getStatus() != 0) {
          setStatus(other.getStatus());
        }
        if (!other.getMessage().isEmpty()) {
          message_ = other.message_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        mech.mania.engine.domain.model.InfraProtos.InfraStatus parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (mech.mania.engine.domain.model.InfraProtos.InfraStatus) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int status_ ;
      /**
       * <code>int32 status = 1;</code>
       * @return The status.
       */
      @java.lang.Override
      public int getStatus() {
        return status_;
      }
      /**
       * <code>int32 status = 1;</code>
       * @param value The status to set.
       * @return This builder for chaining.
       */
      public Builder setStatus(int value) {
        
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 status = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearStatus() {
        
        status_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object message_ = "";
      /**
       * <code>string message = 2;</code>
       * @return The message.
       */
      public java.lang.String getMessage() {
        java.lang.Object ref = message_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          message_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string message = 2;</code>
       * @return The bytes for message.
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        java.lang.Object ref = message_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string message = 2;</code>
       * @param value The message to set.
       * @return This builder for chaining.
       */
      public Builder setMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        message_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string message = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMessage() {
        
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }
      /**
       * <code>string message = 2;</code>
       * @param value The bytes for message to set.
       * @return This builder for chaining.
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        message_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:infra.InfraStatus)
    }

    // @@protoc_insertion_point(class_scope:infra.InfraStatus)
    private static final mech.mania.engine.domain.model.InfraProtos.InfraStatus DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new mech.mania.engine.domain.model.InfraProtos.InfraStatus();
    }

    public static mech.mania.engine.domain.model.InfraProtos.InfraStatus getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<InfraStatus>
        PARSER = new com.google.protobuf.AbstractParser<InfraStatus>() {
      @java.lang.Override
      public InfraStatus parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new InfraStatus(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<InfraStatus> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<InfraStatus> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public mech.mania.engine.domain.model.InfraProtos.InfraStatus getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_infra_InfraPlayer_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_infra_InfraPlayer_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_infra_InfraVisualizer_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_infra_InfraVisualizer_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_infra_InfraStatus_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_infra_InfraStatus_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013infra.proto\022\005infra\"5\n\013InfraPlayer\022\023\n\013p" +
      "layer_name\030\001 \001(\t\022\021\n\tplayer_ip\030\002 \001(\t\"1\n\017I" +
      "nfraVisualizer\022\036\n\026visualizer_connect_url" +
      "\030\001 \001(\t\".\n\013InfraStatus\022\016\n\006status\030\001 \001(\005\022\017\n" +
      "\007message\030\002 \001(\tB>\n\036mech.mania.engine.doma" +
      "in.modelB\013InfraProtos\252\002\016MM26.IO.Modelsb\006" +
      "proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_infra_InfraPlayer_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_infra_InfraPlayer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_infra_InfraPlayer_descriptor,
        new java.lang.String[] { "PlayerName", "PlayerIp", });
    internal_static_infra_InfraVisualizer_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_infra_InfraVisualizer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_infra_InfraVisualizer_descriptor,
        new java.lang.String[] { "VisualizerConnectUrl", });
    internal_static_infra_InfraStatus_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_infra_InfraStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_infra_InfraStatus_descriptor,
        new java.lang.String[] { "Status", "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
